@echo off
title ESP32 一键烧录工具

REM ============ 可选覆盖配置（一般无需修改，留空自动检测） ============
REM 手动指定 ESP-IDF 环境激活脚本；留空 = 从脚本所在目录逐级向上查找 idf-env.bat
set "IDF_ENV_BAT="
REM 默认串口（电脑上只检测到 1 个串口时会自动改用它）
set "DEFAULT_PORT=COM15"
REM 自动部署用：ESP-IDF 版本标签与克隆源（国内慢可换 gitee 镜像
REM   https://gitee.com/EspressifSystems/esp-idf.git，子模块仍走 github）
set "IDF_VERSION_TAG=v6.1"
set "IDF_GIT_URL=https://github.com/espressif/esp-idf.git"
REM ====================================================================

echo ==============================================
echo      ESP32 一键 编译 / 烧录 / 串口监视
echo ==============================================

REM ----- [1/4] 定位工程目录与环境激活脚本 -----
REM 工程目录 = 脚本所在目录（脚本放工程根目录，整个文件夹挪走也不用改路径）
cd /d "%~dp0"
set "PROJECT_DIR=%CD%"

if not exist "%PROJECT_DIR%\CMakeLists.txt" echo [警告] 当前目录无 CMakeLists.txt，脚本可能不在 ESP-IDF 工程根目录

if defined IDF_ENV_BAT goto env_ready
set "SEARCH_DIR=%PROJECT_DIR%"
:search_loop
if exist "%SEARCH_DIR%\idf-env.bat" (
    set "IDF_ENV_BAT=%SEARCH_DIR%\idf-env.bat"
    goto env_ready
)
for %%j in ("%SEARCH_DIR%\..") do set "NEXT_DIR=%%~fj"
if "%NEXT_DIR%"=="%SEARCH_DIR%" goto env_missing
set "SEARCH_DIR=%NEXT_DIR%"
goto search_loop

REM ===== 未找到环境：询问是否自动部署 =====
:env_missing
echo.
echo [提示] 本机未找到 ESP-IDF 开发环境（已从工程目录逐级向上搜索到盘符根目录）
choice /c YN /t 30 /d N /m "是否自动部署 ESP-IDF（克隆源码+下载工具链，约 2~3GB / 10~30 分钟）"
if errorlevel 2 goto manual_hint

REM 部署前置检查：git 与 python 必须可用
git --version >nul 2>&1
if errorlevel 1 (
    echo [错误] 未检测到 git，无法自动部署，请先安装 Git for Windows
    goto manual_hint
)
python --version >nul 2>&1
if errorlevel 1 (
    echo [错误] 未检测到 python，无法自动部署，请先安装 Python 3.9 以上版本
    goto manual_hint
)

for %%j in ("%PROJECT_DIR%\..") do set "PROJECT_PARENT=%%~fj"
set "IDF_INSTALL_DIR=%PROJECT_PARENT%\esp-idf"
set "USER_INPUT="
set /p USER_INPUT=ESP-IDF 安装位置（直接回车 = %IDF_INSTALL_DIR%）:
if not "%USER_INPUT%"=="" set "IDF_INSTALL_DIR=%USER_INPUT%"

if exist "%IDF_INSTALL_DIR%\export.bat" (
    echo [提示] %IDF_INSTALL_DIR% 已存在 ESP-IDF，跳过克隆
    goto deploy_install
)

echo [部署 1/3] 克隆 ESP-IDF %IDF_VERSION_TAG%（浅克隆，下载量最小）...
git clone --recursive --depth 1 --shallow-submodules -b %IDF_VERSION_TAG% %IDF_GIT_URL% "%IDF_INSTALL_DIR%"
if errorlevel 1 (
    echo [错误] 克隆失败：网络不通或版本标签不存在
    echo        可编辑脚本顶部 IDF_GIT_URL 换镜像源后重试
    pause
    exit /b 1
)

:deploy_install
echo [部署 2/3] 安装 xtensa 工具链与 Python 虚拟环境（下载走 Espressif 官方镜像）...
for %%j in ("%IDF_INSTALL_DIR%\..") do set "DEPLOY_PARENT=%%~fj"
set "IDF_TOOLS_PATH=%DEPLOY_PARENT%\esp-idf-tools"
set "IDF_GITHUB_ASSETS=dl.espressif.com/github_assets"
set "PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple"
cd /d "%IDF_INSTALL_DIR%"
call install.bat esp32
if errorlevel 1 (
    echo [错误] 工具链安装失败：请检查网络后重新运行本脚本（已克隆的源码会保留续用）
    pause
    exit /b 1
)

echo [部署 3/3] 生成环境激活脚本：%PROJECT_PARENT%\idf-env.bat
(
    echo @echo off
    echo REM Auto-generated by flash script, safe to delete and re-run deploy
    echo set "MSYSTEM="
    echo set "PYTHONUTF8=1"
    echo set "IDF_SKIP_TOOLS_CHECK=1"
    echo set "IDF_TOOLS_PATH=%IDF_TOOLS_PATH%"
    echo set "IDF_PATH=%IDF_INSTALL_DIR%"
    echo set "IDF_TARGET=esp32"
    echo set "IDF_GITHUB_ASSETS=dl.espressif.com/github_assets"
    echo call "%%IDF_PATH%%\export.bat"
    echo if errorlevel 1 exit /b 1
) > "%PROJECT_PARENT%\idf-env.bat"
set "IDF_ENV_BAT=%PROJECT_PARENT%\idf-env.bat"
echo [部署完成] 后续双击本脚本将直接使用该环境，不再重复部署
goto env_ready

:manual_hint
echo.
echo 手动部署方案：
echo   1. 官方 Windows 安装器（图形界面，自带全部工具，推荐新手）：
echo      https://dl.espressif.com/dl/esp-idf/
echo   2. 本机已有环境：编辑脚本顶部 set "IDF_ENV_BAT=" 填入 idf-env.bat 完整路径
pause
exit /b 1

:env_ready
echo.
echo [1/4] 环境激活脚本：%IDF_ENV_BAT%
call "%IDF_ENV_BAT%"
if errorlevel 1 (
    echo [错误] ESP-IDF 环境激活失败，请检查该脚本内容
    pause
    exit /b 1
)
cd /d "%PROJECT_DIR%"

REM ----- [2/4] 开发环境自检（idf.py 可运行即环境完整） -----
set "IDF_VERSION="
for /f "delims=" %%v in ('idf.py --version 2^>nul') do set "IDF_VERSION=%%v"
if not defined IDF_VERSION (
    echo [错误] idf.py 无法运行：ESP-IDF 未正确安装或环境脚本有误
    pause
    exit /b 1
)
echo [2/4] 开发环境自检：通过
echo       %IDF_VERSION%
echo       工程目录：%PROJECT_DIR%

REM ----- [3/4] 枚举串口并选择 -----
echo.
echo [3/4] 检测到的串口设备：
echo --------------------------------------------------
powershell -NoProfile -Command "Get-CimInstance Win32_PnPEntity | Where-Object { $_.Name -match '\(COM\d+\)' } | ForEach-Object { '   ' + $_.Name }" 2>nul
if errorlevel 1 echo   （串口枚举失败，仍可手动输入串口号继续）
echo --------------------------------------------------

REM 仅检测到 1 个串口时自动作为默认值
set "PORT_COUNT=0"
set "PORT_LIST="
for /f "tokens=1,2" %%a in ('powershell -NoProfile -Command "$p=@([System.IO.Ports.SerialPort]::GetPortNames()); '{0} {1}' -f $p.Count, ($p -join ' ')"') do (
    set "PORT_COUNT=%%a"
    set "PORT_LIST=%%b"
)
if "%PORT_COUNT%"=="1" set "DEFAULT_PORT=%PORT_LIST%"
if "%PORT_COUNT%"=="1" echo   仅检测到一个串口，自动作为默认：%PORT_LIST%
echo.

set "COM_PORT=%DEFAULT_PORT%"
set "USER_INPUT="
set /p USER_INPUT=请输入串口号（数字或 COMx，直接回车 = %DEFAULT_PORT%）:
if not "%USER_INPUT%"=="" set "COM_PORT=%USER_INPUT%"

REM 纯数字输入自动补 COM 前缀
echo %COM_PORT%| findstr /r /i "^com[0-9][0-9]*$" >nul || set "COM_PORT=COM%COM_PORT%"

REM 校验串口存在且未被占用（试开即关，不改动任何设置）
powershell -NoProfile -Command "try { $p = New-Object System.IO.Ports.SerialPort('%COM_PORT%'); $p.Open(); $p.Close(); exit 0 } catch { exit 1 }"
if errorlevel 1 (
    echo [错误] 无法打开 %COM_PORT%：串口号不对，或被其他程序占用
    pause
    exit /b 1
)

REM ----- [4/4] 编译 + 烧录 + 监视（idf.py 链式完成，自动增量编译） -----
echo.
echo [4/4] 目标串口：%COM_PORT%，开始编译并烧录，完成后自动进入串口监视...
echo       监视模式退出快捷键：Ctrl+]
echo.
idf.py -p %COM_PORT% flash monitor

echo.
echo ==============================================
echo  流程结束（监视已退出），窗口可关闭。
echo ==============================================
pause
